### ISSUE TITLE
Single java file without workspace doesn't work well in codespace

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-java-pack#1286] opened 2024-02-01 08:07 UTC
**Environment:**

- VS Code Version: Github Codespace
- Extension Version: 1.27.0
- JDK Type & Version: java 21
- OS Type & Version: windows

**Step to Reproduce:**
1. Clone https://github.com/redhat-developer/vscode-java to your local folder
2. In codesapce, open an empty window
3. Drag a java file vscode-java/blob/master/test/resources/projects/eclipse/simple-app/src/app/App.java to it

**Expected Behavior:**
1. Has Run/Debug actions in editor 
2. Can run successfully
3. Refresh codespace in browser > Can load the java file well

**Actual Behavior:**
1. No Run/Debug actions in editor 
2. Fail to run with below error
3. Refresh codespace in browser > Cannot load the java file
![image](https://github.com/microsoft/vscode-java-pack/assets/31497677/a2430eb9-a8eb-4fca-8878-b98f88675837)
![image](https://github.com/microsoft/vscode-java-pack/assets/31497677/773f9234-7432-4221-b01a-ef5166b23352)

**Comment by loralei28** [comment] 2024-02-01 10:17
"UNC host 'wsl.localhost' access is not allowed" appears on os-WSL, and the result does not change after setting settings according to the information.
![image](https://github.com/microsoft/vscode-java-pack/assets/108506566/9b4546f7-8681-4231-b98f-a1ec637bfada)

**Comment by testforstephen** [comment] 2024-02-04 08:19
By design. When you drag a single file to a remote workspace, you are moving it between different file systems and network environments. I don't think the Java extension supports this kind of use case for single files.

**Closed by testforstephen** 2024-02-04 08:19 UTC
Labels: codespace
