### ISSUE TITLE
Cannot debug a single file when no workspace folder is opened

### ISSUE THREAD

**Issue by VivekHalakatti** [microsoft/vscode-java-pack#832] opened 2021-11-29 19:38 UTC
**Environment:Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)**

- VS Code Version:1.62.3
- Extension Version:
- JDK Type & Version: java 17.0.1 2021-10-19 LTS
                                      Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
                                      Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
- OS Type & Version: MacOS & Monterey
**Step to Reproduce:I have installed JDK correctly and all files are in the right directory. But i am unable to run any java programs using text editors such as VS code, sublime.They do not show any error either! just blank space.i have tried multiple text editors with java code and none are working. But the same works when done in terminal explicitly**

**Expected Behavior:They have too run atleast simple programs other than printing strings.I am unable to do anything 
other than printing strings.Incapable to show the outputs of the performed computations**

**Actual Behavior:No output of computations other than string.**

**Related Issues:**

**Comment by Eskibear** [comment] 2021-11-30 03:06
Have you installed Java Extension Pack including the debugger extension? Please follow this: https://code.visualstudio.com/docs/java/java-tutorial#_running-and-debugging-your-program

Let me know if it works. 

BTW, it's running, awaiting for user input. Looks like you are running Java program from other extension (like CodeRunner).

**Comment by VivekHalakatti** [comment] 2021-11-30 13:56
> Have you installed Java Extension Pack including the debugger extension? Please follow this: https://code.visualstudio.com/docs/java/java-tutorial#_running-and-debugging-your-program
> 
> Let me know if it works.
> 
> BTW, it's running, awaiting for user input. Looks like you are running Java program from other extension (like CodeRunner).

Thank you for your early response😄. Yes i have installed all the needed extensions, i still am facing the same problem.

**Comment by testforstephen** [comment] 2021-12-01 05:41
You're using Code Runner to run your Java code, that's not contributed by vscode-java-pack. Could you pls try "Run Java"/"Debug Java" button?

![image](https://user-images.githubusercontent.com/14052197/144178117-9bad6951-490d-4e4a-8f37-eb1734a97c8e.png)

**Comment by VivekHalakatti** [comment] 2021-12-01 07:36
> You're using Code Runner to run your Java code, that's not contributed by vscode-java-pack. Could you pls try "Run Java"/"Debug Java" button?
> 
> ![image](https://user-images.githubusercontent.com/14052197/144178117-9bad6951-490d-4e4a-8f37-eb1734a97c8e.png)

Yes, i have tried that too. Nothing happens when i click on "Run java".

**Comment by VivekHalakatti** [comment] 2021-12-01 07:37
Could you please connect to me via teamviewer or any other screen sharing app and get me through this?

**Comment by VivekHalakatti** [comment] 2021-12-01 07:38
> > You're using Code Runner to run your Java code, that's not contributed by vscode-java-pack. Could you pls try "Run Java"/"Debug Java" button?
> > ![image](https://user-images.githubusercontent.com/14052197/144178117-9bad6951-490d-4e4a-8f37-eb1734a97c8e.png)
> 
> Yes, i have tried that too. Nothing happens when i click on "Run java".

Could you please connect to me via teamviewer or any other screen sharing app and get me through this?

**Comment by testforstephen** [comment] 2021-12-01 07:52
We launch your application in **TERMINAL** view, could you check your TERMINAL view?

**Comment by VivekHalakatti** [comment] 2021-12-01 08:10
> We launch your application in **TERMINAL** view, could you check your TERMINAL view?

Program execution is proper when done in terminal. But it is  not working through visual code.
<img width="577" alt="Screens
<img width="1422" alt="Screenshot 2021-12-01 at 1 27 28 PM" src="https://user-images.githubusercontent.com/65499521/144195999-9abbf3f0-ddfb-4ee2-b63c-ece0d825cd48.png">
hot 2021-12-01 at 1 36 24 PM" src="https://user-images.githubusercontent.com/65499521/144195984-65a425ae-7a89-423f-abec-bf884be1f25b.png">

**Comment by VivekHalakatti** [comment] 2021-12-01 08:14
Java program execution is proper when done directly through terminal but when executing the same using visual studio ,it is not working properly. For example, in the image below it is not accepting any input in Visual studio. But in terminal(second image) everything works fine.
<img width="1422" alt="Screenshot 2021-12-01 at 1 27 28 PM" src="https://user-images.githubusercontent.com/65499521/144196526-e
<img width="577" alt="Screenshot 2021-12-01 at 1 36 24 PM" src="https://user-images.githubusercontent.com/65499521/144196543-14fc2933-cccb-406a-afc4-44c42981a6aa.png">
f68dc1a-5aaf-4fa9-88fc-3db21924e6c7.png">

**Comment by VivekHalakatti** [comment] 2021-12-01 08:15
Java program execution is proper when done directly through terminal but when executing the same using visual studio ,it is not working properly. For example, in the image below it is not accepting any input in Visual studio. But in terminal(second image) everything works fine
<img width="1422" alt="VS" src="https://user-images.githubusercontent.com/65499521/144196836-5a34d281-80e8-40e5-a29c-47174a0b4cb7.png">
.
<img width="577" alt="Screenshot 2021-12-01 at 1 36 24 PM" src="https://user-images.githubusercontent.com/65499521/144196863-cdca500f-e34c-47f8-871d-d20a00c84efc.png">

**Comment by testforstephen** [comment] 2021-12-01 08:33
https://user-images.githubusercontent.com/14052197/144199448-aadc263f-e2cf-469d-9804-5b83d16d5323.mov

**Comment by Eskibear** [comment] 2021-12-01 08:40
@VivekHalakatti You were using another approach (probably provided by other extensions) to run your project, NOT provided by our extensions.

**Comment by VivekHalakatti** [comment] 2021-12-01 08:49
> Screen.Recording.2021-12-01.at.16.31.09.mov

https://user-images.githubusercontent.com/65499521/144201810-6d942735-2e7e-46aa-8e42-b28d496f8c40.mov

**Comment by Eskibear** [comment] 2021-12-01 08:52
> Note: If you open a Java file in VS Code without opening its folder, the Java Language Server might not work properly.

Please open a folder containing this file. Otherwise it's working in lightweight mode (indicated by the rocket icon in bottom right corner).

**Comment by Eskibear** [comment] 2021-12-01 08:57
@testforstephen I can simply reproduce it by dragging in a .java file without opening any folder. 
- Run Java: silent failure
- Debug Java: silent failure
- F5: silent failure with a debugging toolbar.

We should probably optimize debugger extension for such case. Beginners might get stuck on this due to silent failure.

**Comment by VivekHalakatti** [comment] 2021-12-01 09:08
> > Note: If you open a Java file in VS Code without opening its folder, the Java Language Server might not work properly.
> 
> Please open a folder containing this file. Otherwise it's working in lightweight mode (indicated by the rocket icon in bottom right corner).

Wow,thanks a lot!!. It is working now. I feel so stupid tbh�
<img width="1440" alt="Screenshot 2021-12-01 at 2 34 04 PM" src="https://user-images.githubusercontent.com/65499521/144204712-40936b82-5ae6-414b-9f50-75ba2918ac56.png">
�.

**Comment by VivekHalakatti** [comment] 2021-12-01 09:09
But ,why is coderunner extension stuck without taking any input?
<img width="1440" alt="Screenshot 2021-12-01 at 2 38 44 PM" src="https://user-images.githubusercontent.com/65499521/144205097-bd3bb010-c64e-4bdb-8946-27a44052a4c7.png">

**Comment by Eskibear** [comment] 2021-12-01 09:16
> But ,why is coderunner extension stuck without taking any input?

Basically it's using output channel, which doesn't have the capability to interact with user. You'd better ask author of code runner about it.

**Comment by testforstephen** [comment] 2021-12-01 09:21
There is a regression bug about single file debugging support. https://github.com/redhat-developer/vscode-java/issues/2231

If you opened a single file without a workspace folder, the debugger extension will be broken. The upstream Java language support for Java extension has fixed it and will be released in 1.2.0.

**Comment by VivekHalakatti** [comment] 2021-12-01 09:41
Thank you so much @Eskibear @testforstephen

**Comment by testforstephen** [comment] 2021-12-24 02:12
Closing it since Java Language Support extension @1.2.0 version has fixed this issue.

**Closed by testforstephen** 2021-12-24 02:12 UTC
Labels: external, debug
