### ISSUE TITLE
Support to add Jar file or any other file/directory to classpath

### ISSUE THREAD

**Issue by hemangajmera** [microsoft/vscode-java-pack#94] opened 2019-02-05 13:21 UTC
The extension does not support addition external jar file to the classpath. The only way is to manually add it to .classpath file. Please refer to https://stackoverflow.com/questions/50232557/visual-studio-code-java-extension-howto-add-jar-to-classpath/54535301#54535301

**Comment by akaroml** [comment] 2019-02-15 05:51
@yaohaizh  please help link this issue to vscode-java's new feature of adding Jar dependencies directly.

**Comment by martinkoch-geniebelt** [comment] 2019-08-15 17:48
I'm somewhat of a noob to this, but it seems quite odd to me that this is so difficult. [Stackoverflow](https://stackoverflow.com/questions/50749388/setting-the-classpath-in-a-visual-studio-code-maven-based-java-project) suggests a solution, but that doesn't work for me. I've tried both absolute and relative referencing of the jar file, putting the .classpath file in various locations, but it seems that vscode ignores it entirely. Any suggestions will be appreciated :) (I'd prefer a solution that works with the vanilla javac, e.g. without having to install maven)

**Comment by akaroml** [comment] 2019-10-25 04:58
@Vigilans please take a look at this issue. Users are looking for a way of adding dependencies to their projects.

**Comment by nimr77** [comment] 2019-10-30 02:30
It's so easy, anyway:
0. Creat project with java ctrl+shift+p
1. add the jar file to your .classpath
2. add on the top of your project package [app]; the name of your package
3. We are done, don't forget to refresh it.

**Comment by akaroml** [comment] 2019-12-03 06:48
We are in the process of adding a UI entry for this. @vigilans is on this.

**Comment by jdneo** [comment] 2020-01-13 02:26
Close this since https://github.com/microsoft/vscode-java-dependency/pull/213 is merged. It will be available in the next version of `Java Dependency Viewer`.

**Closed by jdneo** 2020-01-13 02:26 UTC
Labels: enhancement

**Comment by husseinkohy** [comment] 2020-03-13 19:55
> Start from `Language Support for Java@0.55.0`, we added a new setting `java.project.referencedLibraries` to config the project classpaths. Please see [this link](https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224) for usage guide.
> 
> Meanwhile, in order to improve the UX, we had this [PR](https://github.com/microsoft/vscode-java-dependency/pull/213) to let the users be able to config this setting from the Dependency Explorer, which will be available in the next version of `Java Dependency Viewer`:
> ![demo](https://user-images.githubusercontent.com/6193897/72230841-0aa2fc00-35f3-11ea-8d8b-8ec9f04123ad.gif)
> 
> Close this issue for now, but please feel free to let us know if you have any thoughts on this.
> 
> Thanks.

java.project.refe.. libs in mac os is not working. it is not a multiroot project, etc all java dependencies installed. thanks

**Comment by jdneo** [comment] 2020-03-14 03:21
@husseinkohy What kind of project are you working on?

Let's say, Can you see files like `.project`, '.classpath' in your project's root path?

**Comment by husseinkohy** [comment] 2020-03-14 14:59
thanks guys for responding. it is an https://ant.apache.org/ivy/ivyde/ project. yes .classpath and .projects are there, what is not resolving in .classpath is ref's like this.

<classpathentry kind="con" path="org.apache.ivyde.eclipse.cpcontainer.IVYDE_CONTAINER/?project=....

i could add the jar's individually as <classpathentry kind="lib" path="absolute path to a jar"....> but that would not be the ideal way.
there is a plugin (https://archive.codeplex.com/?p=ivyvisual) but it is not in .vscode market place

**Comment by jdneo** [comment] 2020-03-15 03:16
I see. Just as you said, some of the classpathentries needs to be solved by the specific `IvyDE` plugin, while this plugin is not support VS Code right now. So I'm afraid you have to use the workaround you have mentioned right now.

**Comment by mp768** [comment] 2020-03-22 14:19
can you give a tutorial on how to set up through video, because I'm not entirely understanding it.

**Comment by jdneo** [comment] 2020-03-23 01:04
@mp768 What kind of project are you using?
- Maven/Gradle
- Eclipse (no pom.xml or build.gradle, but you can see .classpath/.project on the project root path)
- Standalone (no pom.xml, build.gradle, .classpath, .project)

**Comment by brunoborges** [comment] 2020-03-31 05:57
Confirmed: not working on macOS. Tried with a "naked" project.

**Comment by micheledellaciana1** [comment] 2020-04-07 23:15
Hi, I'm trying too to use referencedLibraries to include libraries, but it doesn't work... no effect at all and I work on windows 10.

I see also that using java dependency you can add external lib with the interface, (using the add button in the corner). I haven't the button, and folders are labeled with (Read-only).

By now the only way I can add external lib is to typing directly the classpath file.

<img width="246" alt="Cattura" src="https://user-images.githubusercontent.com/46371841/78727899-3a357c00-7936-11ea-8060-5d0038258c6c.PNG">

WIth eclipse, no problem to add libs in the same project. 

Thk in advice for help

**Comment by jdneo** [comment] 2020-04-08 01:27
@micheledellaciana1 I guess your project is an Eclipse project, which is so far not supported to manage libs in the dependency viewer.

Here, what we supported is the `non-project files/folders`, which means, there is no `.classpath` or `.project` in your project base path.

**Comment by micheledellaciana1** [comment] 2020-04-09 18:19
ahhh Now I get it! Everything works fine! Many thanks! :))

**Comment by labibhussain** [comment] 2020-04-19 04:21
Is a .classpath file absolutely necessary?

I've been having issues with incorporating .jar files from an external library into my project on vscode. The project was standalone and was not made through a "create Java app" function, so my directory does not contain an .classpath files. However, I was able to add the necessary .jar files to a lib file as well as have the Java Dependency View recognize the two .jar files I wanted to add.

However, when I try to compile a file that imports one of these files, I keep getting compiler errors saying that the package does not exist. Any idea as to what the issue could be? Here are a few pictures of the jar files located in my directory:
<img width="314" alt="Screen Shot 2020-04-19 at 12 20 30 AM" src="https://user-images.githubusercontent.com/37557870/79679386-b2702d00-81d3-11ea-9008-39e6db428c4d.png">
<img width="308" alt="Screen Shot 2020-04-19 at 12 20 14 AM" src="https://user-images.githubusercontent.com/37557870/79679387-b2702d00-81d3-11ea-801f-2540f6db4233.png">

**Comment by gerrywp** [comment] 2020-11-27 00:30
> Start from `Language Support for Java@0.55.0`, we added a new setting `java.project.referencedLibraries` to config the project classpaths. Please see [this link](https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224) for usage guide.
> 
> Meanwhile, in order to improve the UX, we had this [PR](https://github.com/microsoft/vscode-java-dependency/pull/213) to let the users be able to config this setting from the Dependency Explorer, which will be available in the next version of `Java Dependency Viewer`:
> ![demo](https://user-images.githubusercontent.com/6193897/72230841-0aa2fc00-35f3-11ea-8d8b-8ec9f04123ad.gif)
> 
> Close this issue for now, but please feel free to let us know if you have any thoughts on this.
> 
> Thanks.

你好，请问怎么引用本地的.class字节码文件夹呢？这里只能添加.jar包，并不能添加一个包含.class文件的包的目录噢！

**Comment by jdneo** [comment] 2020-11-27 01:41
@gerrywp It's only supporting jar file right now, please feel free to create [new feature requests here](https://github.com/microsoft/vscode-java-dependency/issues) if you want more support

**Comment by HuskyNator** [comment] 2021-02-15 01:36
What about adding it to projects that use maven? Those don't show a "Reference Libraries" section 😞

**Comment by jdneo** [comment] 2021-02-16 04:09
@HuskyNator we recommend to directly update the pom file, since that is the source of the truth of what the project build process. (otherwise, the build result in VS Code might be different from that in CI/CD). 

BTW, we do have the [same request here](https://github.com/microsoft/vscode-java-dependency/issues/218). Please feel free to upvote it. If more and more people are requesting for it. We will consider to support this feature.

**Comment by kartercs** [comment] 2022-07-06 14:42
Hello,

i'm not sure i'm in the right place but i have been searching for days how to handle the eclipse project USER_LIBRARYS i have.

My project is a Eclipse project with the .classpath and .project visible in vscode, my coworkers all use Eclipse and they have those two files in version control, so i can't delete or modify it (at least i can't delete entry in the .classpath).

my classpath file looks like this :  
`
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry excluding=".classpath|.gitattributes|.gitignore|.project|.settings/|branch.properties|build.xml|common-lib.xml/" kind="src" path=""/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/JAVATOOLS18"/>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/COMMON_MASTER"/>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/COMMON_DMPV2"/>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/COMMON_DMP"/>
	<classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/JEEBOP_MSSPRO"/>
</classpath>
`
 and the Java project window show me all the entry like this : 
![image](https://user-images.githubusercontent.com/19304535/177574495-6482cac4-0e43-4a05-aade-0a2cd308a2ef.png)

The JRE.CONTAINER is found and all the libs are ok for this one, but all the others are totaly empty ( should have about 80 libs in those ).

As the project is "_managed_" the use of "_java.project.referencedLibraries_" doesn't work and i can't add the jar manually either since everything is readOnly in the "Configure Classpath" 

I'm sorry for digging this up but i'm really lost on this..

Is it just not supported and i have to use eclipse, do i need to try to find a way to remove the .classpath and .project of the version control so i can use "_java.project.referencedLibraries_" or is there a way i make it work in vscode?

**Comment by jdneo** [comment] 2022-07-07 01:55
@kartercs AFAIK, USER_LIBRARY is not supported.

> Or maybe a way to ignore those .classpath and .project so that it is unmanaged and i import all the libs in settings.json?

Should work in this way. If it does not, please let us know.

**Comment by kartercs** [comment] 2022-07-07 08:59
Thanks for your answer @jdneo !

I finnaly made it work by changing names of .classpath and .project files, so that it's unmanaged, but then vscode told me it was not a java project anymore.
I had to add this to settings.json
```json
    "java.project.sourcePaths": ["."],
```
Then i just imported all the libraries in the settings.json and it all worked !

The only "problem" i have between this and eclipse is that the order in which you declare your imports doesn't seem to have an impact on which lib is used, in the .classpath the first libs are always used over the other one if there is a conflct.
Here i tried to put the one i want to be the default in first or in last but it still use the other one.
Do you think there is a way to do this? Or maybe i need to make a feature-request? 

Thanks again for all of this, using eclipse was a nightmare for me !

**Comment by jdneo** [comment] 2022-07-07 11:07
@kartercs So far, the unmanaged folder does not have the concept of import order for those referenced libraries. Please file a feature request for that :)

**Comment by kartercs** [comment] 2022-07-07 13:24
@jdneo Thank you so much for your fast reponses ! 
I just did the feature request if someone need to find it's  there #1023
