### ISSUE TITLE
Strange resolution manner of java language check

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode-java-pack#271] opened 2019-12-05 01:54 UTC
Issue Type: <b>Bug</b>

In my test project, I used Spring and Spring Annotation to write the program. I created an interface called PackageInterface and used getBean() to get the bean of the package. However, when I write
PackageInterface package = (PackageInterface) ac.getBean("package");
, the language checker told me that "PackageInterface cannot be resolved to a variable". I am sure that I imported the interface.

The detailed result is shown below.
![图片](https://user-images.githubusercontent.com/44731563/70196927-32c25400-1745-11ea-86d8-6cc1e3cf74eb.png)

Extension version: 0.8.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.60GB free)|
|Process Argv|--folder-uri file:///e%3A/Moonshot%20Academy/2019.9.2%20-%202020.2/COMP1001%262001%20Computer%20Programming%20I%26II/Advance/projects/SpringPlayground|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by akaroml** [comment] 2019-12-13 09:56
Thanks for letting us know. This looks like the language server fails to resolve the imported type. @testforstephen could you please take a look?

**Comment by stimad** [comment] 2020-07-14 13:56
> Issue Type: Bug
> 
> In my test project, I used Spring and Spring Annotation to write the program. I created an interface called PackageInterface and used getBean() to get the bean of the package. However, when I write
> PackageInterface package = (PackageInterface) ac.getBean("package");
> , the language checker told me that "PackageInterface cannot be resolved to a variable". I am sure that I imported the interface.
> 
> The detailed result is shown below.
> ![图片](https://user-images.githubusercontent.com/44731563/70196927-32c25400-1745-11ea-86d8-6cc1e3cf74eb.png)
> 
> Extension version: 0.8.1
> VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info

This can be really annoying. Can we expect that this will be resolved in near future?

**Comment by testforstephen** [comment] 2020-07-14 14:16
@Power-tile @stimad Could you share a sample project to help reproduce this problem?

**Comment by Power-tile** [comment] 2020-07-14 14:35
Yes I still have the sample project but the error message changed when I reopened vscode. More information:
```PackageInterface``` code:
![image](https://user-images.githubusercontent.com/44731563/87438443-1e6eff80-c622-11ea-9098-886793b8e867.png)
New error message:
![image](https://user-images.githubusercontent.com/44731563/87438500-3181cf80-c622-11ea-823f-1da2cb580ebd.png)
Do you need the entire project for debugging? I could create a repository.

**Comment by testforstephen** [comment] 2020-07-14 14:45
> Do you need the entire project for debugging? I could create a repository.

yes, a reproducible project definitely helps a lot.

**Comment by stimad** [comment] 2020-07-14 15:08
> @Power-tile @stimad Could you share a sample project to help reproduce this problem?

I cannot unfortunately because I don't have permission for that.

**Comment by testforstephen** [comment] 2020-07-14 15:12
> I cannot unfortunately because I don't have permission for that.

@stimad you can remove the sensitive files, and just keep the minimum file that can reproduce the issue.

**Comment by Power-tile** [comment] 2020-07-14 15:36
Update: the old message showed up again:
![image](https://user-images.githubusercontent.com/44731563/87444226-16ff2480-c629-11ea-9f72-268e24d73b63.png)

Sample project link: [https://github.com/Power-tile/shared-projects/tree/spring-java-language-check-bug](https://github.com/Power-tile/shared-projects/tree/spring-java-language-check-bug)

P.S. The "cannot be resolved to variable" message may show up a minute after vscode is fully loaded... The "syntax error on token" message shows up almost immediately after vscode is fully loaded.

**Comment by stimad** [comment] 2020-07-14 16:39
> > I cannot unfortunately because I don't have permission for that.
> 
> @stimad you can remove the sensitive files, and just keep the minimum file that can reproduce the issue.

I'll try it, but it is not constant problem in my case. If I restart vscode everything works nice. Sometimes it appears, sometimes not. I don't know if that is the case with @Power-tile.

**Comment by testforstephen** [comment] 2020-07-15 02:02
```java
PackageInterface package = (PackageInterface)ac.getBean("package");
```

@Power-tile In your sample code, you use `package` as a variable name, which is not allowed because `package` is a Java keyword. When i tried to use a different name for this variable, all errors disappeared. Your issue is not a bug.


@stimad Please share your user case.

**Comment by Power-tile** [comment] 2020-07-15 03:08
That's stupid... Thanks @testforstephen and sorry for inconveniences

**Comment by stimad** [comment] 2020-07-15 07:03
> ```java
> PackageInterface package = (PackageInterface)ac.getBean("package");
> ```
> 
> @Power-tile In your sample code, you use `package` as a variable name, which is not allowed because `package` is a Java keyword. When i tried to use a different name for this variable, all errors disappeared. Your issue is not a bug.
> 
> @stimad Please share your user case.

I will, when be 100% sure how to reproduce problem. Thanks.

**Closed** 2020-08-18 11:22 UTC
Labels: needs more info
