### ISSUE TITLE
Installer v0.2.1: broken jdk MSI installer

### ISSUE THREAD

**Issue by MikusFN** [microsoft/vscode-java-pack#257] opened 2019-11-19 20:52 UTC
installer version: 0.2.1
env:
```
os: win32
arch: x64
PATH: C:\Program Files\Mozilla Firefox;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Gradle\gradle-5.6.2\bin;"C:\Program Files (x86)\Java\jre1.8.0_221\bin;";C:\Users\Miguel\Desktop\Documentos\apache-maven-3.6.2\bin;C:\Users\Miguel\Desktop\Documentos\apache-maven-3.6.2\bin;C:\Users\Miguel\.cargo\bin;C:\Users\Miguel\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2\bin;
JAVA_HOME: C:\Program Files (x86)\Java\jre1.8.0_231
JDK_HOME: undefined
```
log:
```
[8:29:21 PM] Download JDK
[8:40:02 PM] RequestError: Error: read ECONNRESET
[8:40:02 PM] Retry downloading ... [1]
[8:42:22 PM] Download JDK ... [Completed]
[8:42:22 PM] Install JDK
[8:42:25 PM] Error occurred
[8:42:25 PM] Error: Command failed: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Miguel\AppData\Local\Temp\1SMUTcru24NkaZt8Z1nWGxiv0o4\resources\binaries\jdk\8\x64\OpenJDK8U-jdk_x64_windows_hotspot_8u232b09.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\Miguel\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive

T�h�i�s� �i�n�s�t�a�l�l�a�t�i�o�n� �p�a�c�k�a�g�e� �c�o�u�l�d� �n�o�t� �b�e� �o�p�e�n�e�d�.� � �V�e�r�i�f�y� �t�h�a�t� �t�h�e� �p�a�c�k�a�g�e� �e�x�i�s�t�s� �a�n�d� �t�h�a�t� �y�o�u� �c�a�n� �a�c�c�e�s�s� �i�t�,� �o�r� �c�o�n�t�a�c�t� �t�h�e� �a�p�p�l�i�c�a�t�i�o�n� �v�e�n�d�o�r� �t�o� �v�e�r�i�f�y� �t�h�a�t� �t�h�i�s� �i�s� �a� �v�a�l�i�d� �W�i�n�d�o�w�s� �I�n�s�t�a�l�l�e�r� �p�a�c�k�a�g�e�.�
�
�

```

**Comment by Eskibear** [comment] 2019-11-20 08:42
From the log we can see that you have a JRE installed before instead of a JDK (which is required by vscode-java), thus the installer tried download & install an OpenJDK for you. 

> This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.

Possibly because something was wrong during the re-downloading. You may give it a retry and see if it's working. Meanwhile I'll investigate the "retry downloading" logic.

**Comment by Eskibear** [comment] 2020-04-03 10:16
looks similar with #328 

BTW, our installer v0.2.4 has been released with detailed MSI logs recorded. I'm closing it as you are not able to reproduce it in later runs.  But, if you are able to reproduce it in the future, please find and attach file `%temp%\vscode-java-installer\log.txt` and `%temp%\AdoptOpenJDK-MSI.log` here and re-open the issue, thanks.

**Closed by Eskibear** 2020-04-03 10:16 UTC
Labels: installer
