### ISSUE TITLE
Installer v0.2.2: spawn path-to-code.cmd ENOENT

### ISSUE THREAD

**Issue by eliasliasu** [microsoft/vscode-java-pack#292] opened 2020-01-14 09:32 UTC
installer version: 0.2.2
env:
```
os: win32
arch: x64
PATH: C:\Program Files\Amazon Corretto\jdk11.0.5_10\bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Java\jdk-13.0.1\bin;C:\Go\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Users\Tunde\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Tunde\AppData\Local\Programs\Python\Python37\;C:\Users\Tunde\AppData\Local\Microsoft\WindowsApps;C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Tunde\.dotnet\tools;C:\Users\Tunde\go\bin;C:\Users\Tunde\AppData\Local\Microsoft\WindowsApps;C:\Users\Tunde\AppData\Local\GitHubDesktop\bin;C:\Users\Elias Liasu\AppData\Roaming\npm
JAVA_HOME: C:\Program Files\Amazon Corretto\jdk11.0.5_10
JDK_HOME: undefined
```
log:
```
[10:30:49 AM] Configure Java Settings
[10:30:49 AM] Configure Java Settings ... [Completed]
[10:30:49 AM] Install Java Extensions
[10:30:49 AM] Error occurred
[10:30:49 AM] Error: Command failed with ENOENT: C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd --install-extension vscjava.vscode-java-pack
spawn C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT
The system cannot find the path specified.

```

**Comment by eliasliasu** [comment] 2020-01-14 09:36
I got the error this error response while installing the visual studio Java pack installer. The error showed up when i clicked install after my jdk and vscode was recognized by the setup

**Comment by Eskibear** [comment] 2020-01-14 14:13
Someone else also got the same error before. The installer could not install the extension pack for you, because it didn't find VS Code CLI `code.cmd`. (But in others' cases, `code.cmd` was there in the correct location.)

The workaround is that, you manually install the Java extension pack in your VS Code. The installer has configured the settings, and it should work automatically.

> spawn C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT

BTW, to help us understand the wired problem and improve the installer, can you double check if `C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd` exists in your local machine. And have you done some tricks to your `cmd.exe`? We just cannot reproduce the error, and cannot figure out why the error occurs.

**Comment by Eskibear** [comment] 2020-01-14 16:45
@eliasliasu 
I just created a private build [HERE](https://vscjavaci.blob.core.windows.net/vscodejavainstaller/latest/VSCode-Java-Installer-Win-Online-0.2.2-execFile-20200114.1.exe) as suggested by https://github.com/sindresorhus/execa/issues/408#issuecomment-574218242 

Can you give it a try? And let me know if it works, thanks. 

Because it's not signed, you may have to click **More info** and **run it anyway** as shown below:

![image](https://user-images.githubusercontent.com/2351748/72363397-c1a49200-372f-11ea-9a4e-35693baac004.png)

**Comment by Eskibear** [comment] 2020-01-14 16:54
@IuryChagas @husseinrf @taerinlee @prasadpy 
I find that you guys also had the same issue before, with your own machines. If possible, can you try [this private build](https://vscjavaci.blob.core.windows.net/vscodejavainstaller/latest/VSCode-Java-Installer-Win-Online-0.2.2-execFile-20200114.1.exe), and kindly let me know if it works?

Great appreciation.

**Comment by eliasliasu** [comment] 2020-01-15 15:28
Using the private build returned the same error.
However you were absolutely right about the missing path, ,C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd. I don't have this directory.
I suppose this happened while I was changing my user name from "Tunde" to "Elias Liasu". 
I don't know why it's referencing C:\Users\Tunde\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd when I do not have this user agan. The correct path should have been C:\Users\Elias Liasu\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd. I'll try and fix that and retry.

**Comment by Eskibear** [comment] 2020-02-24 13:51
@eliasliasu Is it working after you fix that?

**Comment by eliasliasu** [comment] 2020-02-24 14:08
Yes, it is.

**Comment by Eskibear** [comment] 2020-02-24 15:53
Thank you for the feedback, I'm closing it now.

**Closed by Eskibear** 2020-02-24 15:53 UTC
Labels: bug, installer
