### ISSUE TITLE
Classpath is incomplete. Only syntax errors will be reported

### ISSUE THREAD

**Issue by Zayik** [Microsoft/vscode-java-pack#10] opened 2017-10-26 03:39 UTC
Vs Code pops up the error when viewing java files.  It links user to a site stating what the warning means and how to disable it.

Nowhere does it actually specify how to properly fix the issue. Anyone new to Java development, especially those just starting out will not know how to fix it. Rather than **only** telling them what the warning means and how to disable it, it should link them to a site that shows how to properly fix the issue, in addition to what it currently tells them.

**Comment by andxu** [comment] 2018-03-07 04:06
Duplicate of https://github.com/Microsoft/vscode-docs/issues/1462

**Comment by andxu** [comment] 2018-03-07 04:14
@Zayik Sorry for the delay of finding the issue raised here, with too many gaps in times could you please have a try with the latest version of java pack to see whether it solves your problem?
The main issue address would be: https://github.com/Microsoft/vscode-java-debug/issues

**Comment by yaohaizh** [comment] 2018-06-12 03:01
Close this one as it is tracked by other issue.

**Closed by yaohaizh** 2018-06-12 03:01 UTC
