### ISSUE TITLE
Modifying class name and file name are out of sync

### ISSUE THREAD

**Issue by loralei28** [microsoft/vscode-java-pack#1287] opened 2024-02-01 10:03 UTC
**Environment:**

- VS Code Version:1.85.2
- Extension Version:1.27.0
- JDK Type & Version:17.0.9 <build 17.0.9+9-Ubuntu-122.04>
- OS Type & Version: WSL

**Step to Reproduce:**

1. Clone and open project https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/gradle/simple-gradle
2. Open Foo.java file
3. Click on class name > Rename Symbol > change name to Foo12

**Expected Behavior:**
After modifying the class name or file name, it will be synchronized.
**Actual Behavior:**
![image](https://github.com/microsoft/vscode-java-pack/assets/108506566/a3fb8397-6686-4626-a425-bddcfe5706c3)

**Comment by testforstephen** [comment] 2024-02-05 05:12
Closing it since I cannot reproduce it.

If you rename a class before Java extension is ready (the status bar shows Java: Ready), it won't update the file name.

If this still happens when the Java extension is ready, feel free to reopen it.

**Closed by testforstephen** 2024-02-05 05:12 UTC
Labels: WSL
