### ISSUE TITLE
Bug - New Feature Annotation processing support in Gradle causes more issues than what It should do

### ISSUE THREAD

**Issue by d95776** [microsoft/vscode-java-pack#1134] opened 2023-01-06 02:53 UTC
The new feature annotation processing support in Gradle will generate duplicated source code in java project's classpath - One in bin/generated... folder and the other is the one defined in build.gradle sourceSet (sourceSet definition is required by gradle).  This cause java runtime error. The previous version of vscode works fine because it only recognizes the generated code folder defined in sourceSet.
 
**Environment:**

- VS Code Version: 1.74.1
- Extension Version: Extension Pack for Java v0.25.7
- JDK Type & Version: Openjdk 17
- OS Type & Version:  Mac Montery v12.6.2

**Step to Reproduce:**
In build.gradle includes the following
sourceSets {
    main {
        java {
            srcDirs += 'build/generated/source/apt/main'
        }
    }
}
dependencies {
    implementation 'org.mapstruct:mapstruct-jdk8:1.3.0.Final'
    annotationProcessor "org.mapstruct:mapstruct-processor:1.3.0.Final"
}    

**Expected Behavior:**
Should only recognize the generated code location defined in sourceSets.

**Actual Behavior:**
generate duplicated source code in java project's classpath - One in bin/generated... folder and the other is the one defined in build.gradle sourceSet

**Related Issues:** 
No

**Comment by d95776** [comment] 2023-01-06 03:05
> If you already add the generated folder to your source set, you can disable the AP support in gradle via the setting `java.import.gradle.annotationProcessing.enabled`. In that way, you need to run gradle command line to generate the sources by your own.

Thanks jdneo, could you please provide a solid example to show how to avoide the issue?

**Comment by d95776** [comment] 2023-01-06 03:08
For <Or, if you want the extension automatically keep the generated code up to date, you can remove the sourceSets  section in your gradle file.>
We can't remove seourceSets section because the gradle build requires it and we run gradle automation in a CICD process. We only use vscode java project to run local tests on developer's desktop. We need both but can't have duplicated generated code.

**Comment by d95776** [comment] 2023-01-06 03:29
set "java.import.gradle.annotationProcessing.enabled": false in settings.json makes vscode does not generate source code in bin/generated... folder. That meets our requirements

**Comment by jdneo** [comment] 2023-01-06 03:58
Looks like the issue is resolved, close the issue.

**Closed by jdneo** 2023-01-06 03:58 UTC
Labels: question
