### ISSUE TITLE
Java try-catch command color display problem

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode-java-pack#259] opened 2019-11-21 05:13 UTC
Issue Type: <b>Bug</b>

In the try-catch argument in Java, when I use the operator | to catch for different exception types, the color gets weird when a new line is inserted in the middle of the exception sequences.

try {
process();
} catch (Exception1 | Exception2 | Exception3
| Exception4 | Exception5) { // this is where it gets weird - the catch became yellow and only two of the Exception classes became green
// handle the exception
}

![图片](https://user-images.githubusercontent.com/44731563/69305893-9dad5e80-0c60-11ea-9c76-33127a8afe6b.png)

Extension version: 0.8.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.34GB free)|
|Process Argv|C:\Users\Power_tile\Desktop\COMP2001 Programs\20191120\null-undefined.js|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by akaroml** [comment] 2019-11-27 09:12
Thanks for reporting. @Vigilans please take a look. This is a syntax highlighting issue.
Also add @jdneo and @testforstephen for awareness.

**Comment by Vigilans** [comment] 2019-11-27 09:13
This is duplicate of https://github.com/atom/language-java/issues/205

**Comment by Vigilans** [comment] 2019-11-28 02:30
Fixed in https://github.com/atom/language-java/pull/217.

**Comment by Vlastimil157** [comment] 2020-03-14 02:51
> Issue Type: Bug
> 
> In the try-catch argument in Java, when I use the operator | to catch for different exception types, the color gets weird when a new line is inserted in the middle of the exception sequences.
> 
> try {
> process();
> } catch (Exception1 | Exception2 | Exception3
> | Exception4 | Exception5) { // this is where it gets weird - the catch became yellow and only two of the Exception classes became green
> // handle the exception
> }
> 
> ![图片](https://user-images.githubusercontent.com/44731563/69305893-9dad5e80-0c60-11ea-9c76-33127a8afe6b.png)
> 
> Extension version: 0.8.0
> VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
> OS version: Windows_NT x64 10.0.18362
> 
> System Info

**Comment by Eskibear** [comment] 2020-03-16 04:24
![image](https://user-images.githubusercontent.com/2351748/76723067-fad59e80-6780-11ea-8718-56c50e3d7a17.png)

Verified, it has been fixed.

**Closed by Eskibear** 2020-03-16 04:24 UTC
Labels: bug
