### ISSUE TITLE
VS Code Java Installer Error

### ISSUE THREAD

**Issue by WooojK** [microsoft/vscode-java-pack#207] opened 2019-09-11 14:02 UTC
installer version: 0.1.2
env:
```
os: win32
arch: x64
JAVA_HOME: C:\Program Files\Java\jdk-12.0.2
JDK_HOME: undefined
```
log:
```
[오후 10:59:49] Configure Java Extensions
[오후 10:59:49] Configure Java Extensions ... [Completed]
[오후 10:59:49] Install Java Extensions
[오후 10:59:49] Error occurred
[오후 10:59:49] Error: spawn C:\Users\�����\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT

```

**Comment by Eskibear** [comment] 2019-09-16 01:55
Can you try re-downloading the latest v0.1.3 installer(with the same link), see if the issue is gone?
 
See more in  https://github.com/microsoft/vscode-java-pack/issues/181#issuecomment-530272871

**Comment by Eskibear** [comment] 2019-09-19 05:53
I'm closing it. feel free to reopen if you still suffer the same issue in 0.1.3

**Closed by Eskibear** 2019-09-19 05:53 UTC
Labels: needs more info
