### ISSUE TITLE
Installer v0.2.4: code.exe ENOENT

### ISSUE THREAD

**Issue by BrianZhang1** [microsoft/vscode-java-pack#369] opened 2020-04-21 17:48 UTC
When I try to run the installer, it doesn't work. It returns the error: The system cannot find the path specified.

I notice it tries to install or run some command here:
C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd --install-extension vscjava.vscode-java-pack
spawn C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT
But when I enter the directory: 
C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\
, the bin folder it is trying to access is actually in directory:
C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\_\
instead. It tries to find the bin folder, but it's searching in the wrong place. I'm not sure how to fix this.

installer version: 0.2.4
env:
```
os: win32
arch: x64
PATH: C:\Users\Brian\AppData\Local\Chromium\Application;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Dell\DW WLAN Card;;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Elm\0.19\bin;C:\Users\Brian\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Brian\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\Java\jdk-9.0.1\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\bin;;C:\Users\Brian\AppData\Roaming\npm;C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Brian\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\JetBrains\PyCharm 2019.2\bin;
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[1:42:48 PM] Configure Java Settings
[1:42:49 PM] Configure Java Settings ... [Completed]
[1:42:49 PM] Install Java Extensions
[1:42:49 PM] Error occurred
[1:42:49 PM] Error: Command failed with ENOENT: C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd --install-extension vscjava.vscode-java-pack
spawn C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd ENOENT
The system cannot find the path specified.

```

**Comment by Eskibear** [comment] 2020-04-22 01:38
Thanks for reporting and the investigation. 
Installing Java extensions is the last step, to work it around you just need to install "Java Extension Pack" in VSCode by your own, and then it's all set.

What I'm interested in is why the folder name appended with an underscore. The path it's looking for was found in Windows registry. But from your `PATH` env, I find below entries:
```
C:\Program Files (x86)\Microsoft VS Code\bin;
C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin;
```
The first one is an x86 vscode installed per machine, and the second one is installed per user. I'm wondering if you have installed vscode multiple times and for some reason it's inconsistent with Windows registry. Could you also attach file `%TEMP%\vscode-java-installer\log.txt`?

**Comment by Eskibear** [comment] 2020-04-23 15:33
From the log, I can tell the error is because of missing `C:\\Users\\Brian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code.cmd`.  Posisble root cause can be that you didn't check to install code.cmd during your previous installation of vscode, and the preference was stored into windows registry. We haven't coverred the case yet, but we are looking for alternative ways to install the extensions in such case. 

> Saving java programs in vscode takes around 6 seconds, whereas all my other files
> save immediately. Also, when I try to "run and debug" it, it takes around
> 12 seconds to compile. 

This is definitely abnormal. Does that occur to an arbitrary project or a specific one? If latter, can you describe your project? E.g. Maven or Gradle? Number of sub projects? etc.

**Comment by BrianZhang1** [comment] 2020-04-23 17:26
This mainly happens when I first open vscode. With only java files, the
first time I run one after I open vscode, it will take around 20 seconds.
It can be a simple java program like this one:
public class javaStatic
{
    public static void main(String[] args)
    {
        System.out.println(2 + "je;;p");
    }
}
but it still takes up to 25 seconds to compile it on the first run after I
open vscode. Running it after the first run only takes around 2 seconds
though. I also tested the time it takes to compile with python after
opening vscode, and it only takes 2 seconds. I was thinking that this might
be related to the other java problem I have.

If I take out the folder where all my code is and reinstall vscode, will I
be able to simply open the folder with vscode again? Or will I have to back
my files up some other way?

**Comment by BrianZhang1** [comment] 2020-04-23 19:54
I just reinstalled vscode, and I can install the java pack now. Thanks!

**Comment by Eskibear** [comment] 2020-07-01 05:58
I'm closing it, as we've already removed the hard dependency on `code.cmd`.

**Closed by Eskibear** 2020-07-01 05:58 UTC
Labels: installer
