### ISSUE TITLE
vscode-java-installer v0.2.2 error: 1619 Broken MSI after retry

### ISSUE THREAD

**Issue by 1Gokul** [microsoft/vscode-java-pack#328] opened 2020-03-12 05:11 UTC
installer version: 0.2.2
env:
```
os: win32
arch: x64
PATH: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\viswa\AppData\Local\Microsoft\WindowsApps;C:\Users\viswa\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\viswa\AppData\Local\GitHubDesktop\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[10:28:47 AM] Download JDK
[10:29:14 AM] RequestError: Error: read ECONNRESET
[10:29:14 AM] Retry downloading ... [1]
[10:34:08 AM] RequestError: Error: read ECONNRESET
[10:34:08 AM] Retry downloading ... [2]
[10:41:04 AM] Download JDK ... [Completed]
[10:41:04 AM] Install JDK
[10:41:05 AM] Error occurred
[10:41:05 AM] Error: Command failed with exit code 1619: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\viswa\AppData\Local\Temp\1WBni7p1RXz2l2Ly16XoZJ5Ip8B\resources\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10.msi" MSIINSTALLPERUSER=1 INSTALLDIR="C:\Users\viswa\AppData\Local\Programs\AdoptOpenJDK" ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive
T�h�i�s� �i�n�s�t�a�l�l�a�t�i�o�n� �p�a�c�k�a�g�e� �c�o�u�l�d� �n�o�t� �b�e� �o�p�e�n�e�d�.� � �V�e�r�i�f�y� �t�h�a�t� �t�h�e� �p�a�c�k�a�g�e� �e�x�i�s�t�s� �a�n�d� �t�h�a�t� �y�o�u� �c�a�n� �a�c�c�e�s�s� �i�t�,� �o�r� �c�o�n�t�a�c�t� �t�h�e� �a�p�p�l�i�c�a�t�i�o�n� �v�e�n�d�o�r� �t�o� �v�e�r�i�f�y� �t�h�a�t� �t�h�i�s� �i�s� �a� �v�a�l�i�d� �W�i�n�d�o�w�s� �I�n�s�t�a�l�l�e�r� �p�a�c�k�a�g�e�.�
�
�

```

**Comment by 1Gokul** [comment] 2020-03-12 05:13
It downloaded JDK but failed while installing.

**Comment by 1Gokul** [comment] 2020-03-12 05:17
Also, It installed without any errors when I started the pack installer again.

**Comment by Eskibear** [comment] 2020-03-12 08:58
Looks like a broken MSI package was opened. 
> Also, It installed without any errors when I started the pack installer again.

So in your second run,  was there any retry? If no,  I guess there might be something wrong with the retry, and I might revisit that.

**Comment by 1Gokul** [comment] 2020-03-12 09:35
> So in your second run, was there any retry? 

No, there was no retry when I tried it the second time.

**Comment by Eskibear** [comment] 2020-04-03 10:08
0.2.4 has been released with detailed MSI logs recorded. I'm closing it as you are not able to reproduce it in later runs.  But, if you are able to reproduce it in the future, please find and attach file `%temp%\vscode-java-installer\log.txt` and `%temp%\AdoptOpenJDK-MSI.log` here and re-open the issue, thanks.

**Closed by Eskibear** 2020-04-03 10:08 UTC
Labels: installer

**Comment by 1Gokul** [comment] 2020-04-11 10:23
@Eskibear Sorry for the late reply, but I will do it in case I encounter a similar problem.
