### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ogre2** [microsoft/vscode-java-pack#566] opened 2021-03-11 06:52 UTC
**Environment:**

- VS Code Version: 1.54
- Extension Version: 0.13.0
- JDK Type & Version: openjdk version "11.0.10" 2021-01-19
- OS Type & Version: Windows

**Step to Reproduce:**
- Create a new .java file
- Write some simple executable code.
- Run program.
**Expected Behavior:**
- Program to run.
**Actual Behavior:**
- Error: Failed to lunch debugee in terminal. Reason: b.toLowerCase is not a function.

**Related Issues:**

**Comment by akaroml** [comment] 2021-03-22 07:26
@jdneo please take a look. Looks like a classpath issue.

**Comment by jdneo** [comment] 2021-03-22 07:35
@ogre2 Could you provide more information about how to reproduce the issue? A sample project would be helpful.

**Comment by ogre2** [comment] 2021-03-24 22:27
> @ogre2 Could you provide more information about how to reproduce the issue? A sample project would be helpful.

I wasn't working on anything extensive, merely just testing out the the java-pack with some simple programs that read in data from a file. I've tried uninstalling and reinstalling the extension pack and the issue still persists. I created a simple "hello world" program in a separate directory from the one that I've been using prior that prints to the console, I've pasted it below.

`public class Sample {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}`

When I execute the program, I still get the error "Failed to launch debuggee in terminal. Reason: w.toLowerCase is not a function". Then I'm prompted to open launch.json or cancel. The launch.json file doesn't give any clear answer as to what is prompting this error, but it occurs in every program, in any directory, even after uninstalling, restarting my machine, and reinstalling the extension pack.

**Comment by jdneo** [comment] 2021-03-25 01:58
@testforstephen could you take a look?

**Comment by testforstephen** [comment] 2021-03-25 02:04
@ogre2 thank you for reaching out. Would you mind sharing your user/workspace settings file? If you don't know how to get the settings, see https://code.visualstudio.com/docs/getstarted/settings

**Comment by ogre2** [comment] 2021-03-26 21:22
Sure thing, I've attached the settins.json inside the zipped file. Let me know if there's anything else I can provide.
[settings.zip](https://github.com/microsoft/vscode-java-pack/files/6214404/settings.zip)

**Comment by testforstephen** [comment] 2021-03-30 02:11
```json
    "terminal.integrated.automationShell.windows": [
        "-ExecutionPolicy",
        "Bypass"
    ],
```

Apparently this setting is not valid because it only allows a path as the value. Not sure whether this is the reason for the failure.

**Comment by ogre2** [comment] 2021-04-01 22:12
> ```json
>     "terminal.integrated.automationShell.windows": [
>         "-ExecutionPolicy",
>         "Bypass"
>     ],
> ```
> 
> Apparently this setting is not valid because it only allows a path as the value. Not sure whether this is the reason for the failure.

I went in commented that line out, and it seems to have fixed the issue! The extension runs my code as it should!

**Comment by ogre2** [comment] 2021-04-01 22:13
I missed click, didn't mean to close the issue without properly thanking you guys for helping me troubleshoot the issue. Thanks a lot, I'm gonna enjoy writing more Java on VSCode here on out!

**Comment by testforstephen** [comment] 2021-04-06 07:19
Looks like this issue has been fixed, i will close it. Feel free to comment here if you need more support.

**Closed by testforstephen** 2021-04-06 07:19 UTC
Labels: bug
